### ISSUE TITLE
Contextual Awareness

### ISSUE THREAD

**Issue by ArivAfonso** [onpreeya-srisai/ErNurPs_bot#1]
Hey!! I know this may seem a bit out of place but I am building a virtual assistant and wanted to add the ability to understand the context of my words (like follow-up questions) using dialogflow but I don't know how to implement it. For eg:-
Me: Who painted Mona Lisa
Assistant: Leonardo de Vinci
Me: When was he born?
Assistant: 1475

PS: I know this may seem out of place but this is the closest and most recently updated repo I found

**Comment by onpreeya-srisai** [comment]
Hi, I have read your comment. you drag your mouse (don’t click) to the far
right side of the intent name tab and you will notice the word "Add
follow-up intent" that you can click to see many follow-up types and you
can try it.( Sorry for grammar and Thank you for watching my project)

ในวันที่ พ. 5 พ.ค. 2021 21:27 Ariv ***@***.***> เขียนว่า:

**Comment by onpreeya-srisai** [comment]
> Hey!! I know this may seem a bit out of place but I am building a virtual assistant and wanted to add the ability to understand the context of my words (like follow-up questions) using dialogflow but I don't know how to implement it. For eg:-
> Me: Who painted Mona Lisa
> Assistant: Leonardo de Vinci
> Me: When was he born?
> Assistant: 1475
> 
> PS: I know this may seem out of place but this is the closest and most recently updated repo I found

**Comment by onpreeya-srisai** [comment]
> Hey!! I know this may seem a bit out of place but I am building a virtual assistant and wanted to add the ability to understand the context of my words (like follow-up questions) using dialogflow but I don't know how to implement it. For eg:-
> Me: Who painted Mona Lisa
> Assistant: Leonardo de Vinci
> Me: When was he born?
> Assistant: 1475
> 
> PS: I know this may seem out of place

**Comment by onpreeya-srisai** [comment]
Hi, I have read your comment. you drag your mouse (don’t click) to the far right side of the intent name tab and you will notice the word "Add follow-up intent" that you can click to see many follow-up types and you can try it.
( Sorry for grammar and Thank you for watching my project)

**Comment by ArivAfonso** [comment]
Thanks a lot. Will surely try it
